TS typings
megatolya/plural-ru pull request #1
Opened 2019-09-16 07:37 UTC by igorkamyshev

Привет!

Спасибо за библиотеку, она прекрасно.

Я подумал, что многие люди сейчас стали использовать TypeScript, поэтому было бы здорово добавить TS-тайпинги.

Посмотри, пожалуйста на мои изменения и дай свой фидбек.

2019-11-25 11:58 UTC, megatolya requested changes

2019-11-25 11:58 UTC, megatolya commented on index.d.ts
> +  import { StyleProp, ViewStyle } from 'react-native';
похоже лишнее

2019-11-25 11:58 UTC, megatolya commented on index.d.ts
> +  type GetPlural = (num: numbers, ...forms: Forms) => string;
number?

2019-11-26 17:36 UTC, pavelpuchok requested changes

2019-11-26 17:36 UTC, pavelpuchok commented on index.d.ts
> +  const verb: GetPlural;
Функция `verb` работает только с 3-мя формами, а тип `GetPlural` позволит использовать её с 2-мя формами. Тут надо что-то вроде:
```suggestion
const verb: (num: number, ...forms: ThreeForms) => string;
```

2019-12-02 06:47 UTC, igorkamyshev commented
Спасибо за ревью, правки внес в #2

2019-12-02 06:47 UTC, closed without merging