TS typings
megatolya/plural-ru pull request #2
Opened 2019-12-02 06:47 UTC by igorkamyshev

Привет. Внес правки для #1, но тот пр отредактировать я не могу, потому что удалил свой форк (пр долго висел без ответа и я решил забить 🤣). Посмотри, пожалуйста.

2019-12-03 08:25 UTC, pavelpuchok requested changes

2019-12-03 08:25 UTC, pavelpuchok commented on index.d.ts
> +  type Forms = TwoForms | ThreeForms;
Судя по всему не используется.

2019-12-03 14:00 UTC, igorkamyshev commented on index.d.ts
> +  type Forms = TwoForms | ThreeForms;
Done

2019-12-03 16:59 UTC, pavelpuchok approved these changes

2019-12-09 09:33 UTC, merged

2019-12-09 09:44 UTC, megatolya commented
Супер, спасибо!
Выложил:
```
$ npm info

plural-ru@2.0.2 | MIT | deps: none | versions: 7
Pluralization of russian words in simpliest way
https://github.com/megatolya/plural-ru#readme

keywords: plural, russian, words, pluralization, noun, verb

dist
.tarball: https://registry.npmjs.org/plural-ru/-/plural-ru-2.0.2.tgz
.shasum: 5fda445d7a7f83a94020e3b81266c873a85eebb4
.integrity: sha512-zmQv/tMG7fjF8r8JJ2U1p9dP1RgQ54RnP9nOM9dJHlcWU4mVmesKU9RgouxvyrCIU7lwOtGBYJ6cBa00UlzUZQ==
.unpackedSize: 9.1 kB

maintainers:
- megatolya <forgetthisbox@gmail.com>

dist-tags:
latest: 2.0.2

published just now by megatolya <forgetthisbox@gmail.com>
```